### ISSUE TITLE
FillValue for non-distributed variables?

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/Omega#171]
The comment for `writeNDVar()` states:
``` c++
/// ...A void pointer
/// to a scalar FillValue is also required to fill missing values.
int writeNDVar(void *Variable, ///< [in] variable to be written
               int FileID,     ///< [in] ID of open file to write to
               int VarID       ///< [in] variable ID assigned by defineVar
);
```
However, there is no such `FillValue` argument and the PIO function `PIOc_put_var()` that `writeNDVar()` calls:
https://github.com/E3SM-Project/Omega/blob/871ea4f262161e9a146f10da33f8279f6d66a330/components/omega/src/base/IO.cpp#L793
does not seem to take such an argument:
https://ncar.github.io/ParallelIO/group___p_i_o__put__var__c.html#gabb19e8cc14ebc3da354a59865062a36a

Do we have a plan for how to supply fill values to non-distributed arrays?  It the lack of a fill value going to potentially cause us trouble?  Or do we just need to remove the incorrect comment?

**Comment by philipwjones** [comment]
@xylar As near as I can tell (and don't get me started on pio/netcdf documentation!) the put_var function automatically utilizes the _FillValue provided as a metadata attribute and that's why it's not an explicit argument. Since fill value is a mandatory argument for our field create function, _FillValue should exist for all our fields. I have not actually checked to see whether this is the case in practice. In the end, I'm not sure how many non-distributed arrays we'll have (besides time) in Omega or whether any of them will have missing values.

**Comment by xylar** [comment]
Okay, sounds good.  I'm happy to close this for now and look into it again down the road if a problem emerges.
