### ISSUE TITLE
State unit test is failing on latest develop

### ISSUE THREAD

**Issue by philipwjones** [E3SM-Project/Omega#183]
Across a variety of machines and compilers and both cpu and gpu. It appears to come from the recent halo update PR - the commit that merged master into Brian's branch. Checkout of versions before that still work fine.

**Comment by brian-oneill** [comment]
I've found the issue:

https://github.com/E3SM-Project/Omega/blob/18de8ef099256f275f31662ba4117c019aa840d4/components/omega/test/ocn/StateTest.cpp#L169-L174

Previously, the exchangeHalo function would implicitly initialize the HostArrays for the State variables since the Arrays would be deep copied to the HostArrays, the halo exchanges would be performed on the HostArrays, and then deep copied back to the Arrays. Now those deep copies are removed from OceanState's exchangeHalo function, and the Arrays are getting overwritten by unititialized HostArrays by the copyToDevice in line 173.

I'll confirm with tests on the various machines and then do a PR to fix.
